POST http://localhost:8080/movies
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkBnb2xkZW5jaW5lbWEuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NTE3NjUzOSwiZXhwIjoxNzc1MTgwMTM5fQ.-qhGoQAxWaYxTR1De_G6kxD4juaOceTcAnkytCVhUUNlUUwL1WywvM9lYAQ08cON
Content-Type: application/json

{
  "title": "Inceptiondd",
  "description": "Film science fiction o snach i podświadomości.",
  "durationMinutes": 148,
  "genre": "Sci-Fi",
  "ageRating": "PG-13"
}