spring.profiles.active=dev
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2
server.error.include-message=always
stripe.apiKey=sk_test_51TbGMo3yP3UJYkPbmYuzPriCNyoFfchzWbCyqytb86aXQluyW9qooSIMuoFXhzEqkTrHduLLhObkLqXyARFLkC5C00FLCUyB1e
stripe.webhookSecret=whsec_25f96301f039fdc369a7e40d1652e8c3a85fa3ea21ef7e5d3bf38b310a72f465
stripe.successUrl=http://localhost:3000/success
stripe.cancelUrl=http://localhost:3000/cancel
