spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB:goldencinema}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:goldencinema}
spring.datasource.password=${POSTGRES_PASSWORD:goldencinema}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Disable H2 console if it's not used
spring.h2.console.enabled=false

stripe.apiKey=${STRIPE_API_KEY}
stripe.webhookSecret=${STRIPE_WEBHOOK_SECRET}
stripe.successUrl=${STRIPE_SUCCESS_URL:goldencinema://payment/success}
stripe.cancelUrl=${STRIPE_CANCEL_URL:goldencinema://payment/cancel}