name: Deploy to Mikrus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest


    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.MIKRUS_HOST }}
          username: ${{ secrets.MIKRUS_USER }}
          key: ${{ secrets.MIKRUS_SSH_KEY }}
          port: ${{ secrets.MIKRUS_PORT }}
          script: |
            cd /root/GoldenCinema
            git pull origin main
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -f
